language: r
cache: packages
sudo: false

before_install:
 - Rscript -e 'install.packages("remotes")'
 - Rscript -e 'remotes::install_github("danielcanueto/rDolphin")'
 - Rscript -e 'remotes::install_git("https://gitlab.com/CarlBrunius/MUVR.git")'
 - Rscript -e 'remotes::install_cran("pkgdown")'

r_github_packages:
  - jimhester/covr

jobs:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    packages:
    - r-cran-rcppziggurat
    - r-cran-rfast
    - r-cran-ggplot2
    - r-cran-dplyr
    - r-cran-stringr
    - r-cran-speaq
    - r-cran-biocmanager
    - r-bioc-massspecwavelet
    - r-bioc-impute
    - r-bioc-mixomics
    - r-cran-lubridate
    - r-cran-caret
    - r-cran-shinyjs
    - r-cran-dt
    - r-cran-plotly
